### ISSUE TITLE
Help in creating an Order

### ISSUE THREAD

**Issue by aravchr** [Receiptful/node-woocommerce#17]
Can someone help in the writing the exact code to be written to create an order using this package? This is missing in the docs too

Thanks
Aravind

**Comment by dlebech** [comment]
@aravchr This package is a thin wrapper around the [REST API for WooCommerce](http://woocommerce.github.io/woocommerce-rest-api-docs/) so the documentation for a specific API call can be found there. For example, to [create an order](http://woocommerce.github.io/woocommerce-rest-api-docs/v2.html?shell#create-an-order) using the legacy V2 API (currently the default), you need to wrap the order in an object and use the `/orders` endpoint.

Something like this:
```
var WooCommerce = require('woocommerce');
var wc = new WooCommerce({
  url: 'http://mystore.com',
  consumerKey: 'somekey',
  secret: 'somesecret'
});
var data = {
  order: {
    // Order fields here
  }
};
wc.post('/orders', data)
  .then(() => console.log('success!'));
```
I hope this helps.
