### ISSUE TITLE
Crash for sub folders woocommerce

### ISSUE THREAD

**Issue by riksof-zzlalani** [Receiptful/node-woocommerce#4]
I have woocommerce installed in the sub folder like http://example.com/store

now when I hit this url for get request, the http request causes the node server crash with following error

>events.js:72
>        throw er; // Unhandled 'error' event
>              ^
>Error: getaddrinfo ENOTFOUND
>    at errnoException (dns.js:37:11)
>    at Object.onanswer [as oncomplete] (dns.js:124:16)

**Code**

	var wooOptions = { 
		url: 'example.com/store',
		consumerKey: 'ck_################################',
		secret: 'cs_################################'
	};

	var wooCommerce = new WooCommerce(wooOptions);
							
	wooCommerce.get('/products', function(err, data, resp){
		if ( err ) {

			var message = JSON.parse(err.message)[0].message;
			logger.error(message);
			return;

		}
		console.log("Products", data);
	});

**Comment by RickCraig** [comment]
Hi, Sorry only seeing this now. Let me have a look and see if I can fix this, it will most likely be a fix to gracefully handle the error. If the API can't be found at the path you suggest then I don't think there is anything we can do programmatically.

**Comment by riksof-zzlalani** [comment]
So it wont work for the URLs like `url: 'example.com/store',` ?

**Comment by RickCraig** [comment]
If you type in the url to your store and add '/wc-api/v2' (```http://example.com/store/wc-api/v2```) onto the end in a browser does it show the woocommerce api overview endpoint?

Also I suggest you try the url with the protocol at the start (http | https), as this uses node's built in http/https modules to do the call, and I don't know how well they react to leaving that off. Might not make a difference.

**Comment by riksof-zzlalani** [comment]
If you type in the url to your store and add '/wc-api/v2'. ....

- yes it does.

**Comment by riksof-zzlalani** [comment]
also If I add http in the beginning it throws some error, I dont remember exactly what was the error,

**Comment by RickCraig** [comment]
Ok you will need to give me some time to set up a wordpress site in a folder to see if I can recreate the error, and in turn solve the problem. I will keep you up to date with my progress.

**Comment by RickCraig** [comment]
We recently updated the module to use request which will follow redirects, this should fix the issue you were having. It has also had a small refactor to use es6.
