### ISSUE TITLE
 Cannot set property 'options' of undefined

### ISSUE THREAD

**Issue by digimantra** [Receiptful/node-woocommerce#6]
Hello!

Has anyone fixed this issue yet? Any workaround until we have the solution? This error shows in browser & console both.

 Cannot set property 'options' of undefined
    at WooCommerce (/nodejs/node_modules/woocommerce/lib/woocommerce.js:20:16)
    at Layer.handle [as handle_request] (/nodejs/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/nodejs/node_modules/express/lib/router/index.js:312:13)
    at /nodejs/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/nodejs/node_modules/express/lib/router/index.js:330:12)
    at next (/nodejs/node_modules/express/lib/router/index.js:271:10)
    at expressInit (/nodejs/node_modules/express/lib/middleware/init.js:33:5)
    at Layer.handle [as handle_request] (/nodejs/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/nodejs/node_modules/express/lib/router/index.js:312:13)
    at /nodejs/node_modules/express/lib/router/index.js:280:7

**Comment by RickCraig** [comment]
Could you copy/paste a bit of context for me? Can you show me how you are declaring WooCommerce?

**Comment by digimantra** [comment]
Yes here you go - http://pastebin.com/F97LaPQN

**Comment by RickCraig** [comment]
On line 39 ```app.use('/woo',WooCommerce);``` you are calling 'WooCommerce' directly, it may be a typo, but you maybe wanted to pass 'wooCommerce' in there, as it requires the options to make the connection?

**Comment by RickCraig** [comment]
Also can I make a suggestion, it's a personal preference on the structure, so feel free to disregard:
```javascript
var app = require('express')(),
  WooCommerce = require('woocommerce');

// WooCommerce initialisation
var wooCommerce = new WooCommerce({
  url: 'cityflashsale.com',
  consumerKey: 'mykey',
  secret: 'mysecret',
  logLevel: 0
});

/**
 * Other routes
 */

app.get('/hello', function(req, res) {
  res.send('Hello World');
});

app.get('/auth', function(req, res) {
  var OAuth = require('oauth');
  res.send('requested');
});

/**
 * Products routes
 */

app.get('/products', function(req, res, next) {
  wooCommerce.get('/products', function(err, data) {
    if (err) return next(err);

    // In here I can do any processing
    // that I want to pass to the page

    res.render('/views/products', {
      products: data
    });
  });
});

app.get('/products.json', function(req, res, next) {
  wooCommerce.get('/products', function(err, data) {
    if (err) return next(err);

    // In here I can do anything I want to
    // the data, like sorting, limiting etc

    res.json(data);
  });
});

var server = app.listen(8081, function() {
  console.log(server.address());
  var host = server.address().address
  var port = server.address().port

  console.log("Example app listening at http://%s:%s", host, port)

});
```

**Comment by digimantra** [comment]
Thank you Rick - this perfectly makes sense.
